#!/usr/bin/env bash

#Get ffsend here
#https://github.com/timvisee/ffsend/releases/latest

resp=$($HOME/.local/bin/ffsend u -h https://send.adminforge.de "$1" --expiry-time 5m --password)

url=$(printf "$resp" | grep -oP "https://send.adminforge.de\S+")

printf "$url" | wl-copy; printf "\n\n$url\n"